echo "
JobName: $JOB_NAME
BuildStatus: $BUILD_STATUS
BuildNumber: $BUILD_NUMBER
echo BULDURL: $BUILD_URL
echo NODENAME: $NODE_NAME
echo JOBNAME: $JOB_NAME
echo BUILDTAG: $BUILD_TAG
echo JENINSURL: $JENKINS_URL
echo EXUECUTORNUMBER: $EXECUTOR_NUMBER
echo JAVAHOME: $JAVA_HOME
echo WORKSPACE: $WORKSPACE
echo GITCOMMIT: $GIT_COMMIT
echo GITURL: $GIT_URL
echo GITBRANCH: $GIT_BRANCH"
